### ISSUE TITLE
Proxies

### ISSUE THREAD

**Issue by WabeyF** [ewkt/Vinted-Discord-Notifications#4]
J'ai des erreurs en en utilisant, je prends quel type de proxy ? sous quel format ? Pourriez-vous m'indiquer davantage ?

**Comment by ewkt** [comment]
salut, quel type d'erreur?

pour les proxy c'est des addresses ipv4 qu'on peut mettre dans le fichier, avec ou sans port renseigné

**Comment by WabeyF** [comment]
D'accord mais quel protocole ? (Socks4 ou HTTP ?), as-tu des sites ou je pourrai en trouver pour augmenter la vitesse de requete ? Pourrais-tu expliquer comment tu creer le vinted.db ? Sinon gros GG à ton code !

**Comment by ewkt** [comment]
> D'accord mais quel protocole ? (Socks4 ou HTTP ?), as-tu des sites ou je pourrai en trouver pour augmenter la vitesse de requete ? Pourrais-tu expliquer comment tu creer le vinted.db ? Sinon gros GG à ton code !

ah mince j'ai pas vu ta réponse dsl ajoute moi sur discord si tu veux avori une rep plus rapide :) (thewwk)

mais c'ets des proxy http, on j'ai pas de sites à te proposer dsl
en gros dans le fichier db.js je fais qlq reqyetes sql pour crrer la table en spécifiant le type des données qui vont y être envoyées, puis a chaque fois que j'ai un nouvel artivle je l'ajoute en suivant la structure de ma base!

**Comment by Darshw3b** [comment]
Salut c'est impossible que sa sois du 0 delais tu utilise la route /catalog elle fait 10-15s de delais.

**Comment by ewkt** [comment]
> Salut c'est impossible que sa sois du 0 delais tu utilise la route /catalog elle fait 10-15s de delais.

ça varie vraiment entre la categorie et les recherches, j'ai fait du side by side avec /item et c'est ultra variable les délais entre les deux, le soucis avec /item c'est qu'il faut des proxy etc c'ets un gros investissement pour tout chpper alors que là t'as un bot leger et rapide qui a 0 delais sur /catalog :)
